<?xml version="1.0" encoding="utf-8"?><Database Name="bd_ventas" Class="DataClasesLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSI-GL638RD\SQLEXPRESS01;Initial Catalog=bd_ventas;Integrated Security=True" SettingsObjectName="BaseDeDatos.Properties.Settings" SettingsPropertyName="bd_ventasConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Catalogo" Member="Catalogo">
    <Type Name="Catalogo">
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Factura" Member="Factura">
    <Type Name="Factura">
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Factura_Producto" Member="Producto" ThisKey="Codigo" OtherKey="Fk_Codigo" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fk_Codigo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Factura_Producto" Member="Factura" ThisKey="Fk_Codigo" OtherKey="Codigo" Type="Factura" IsForeignKey="true" />
    </Type>
  </Table>
</Database>